adding basic post creation
agugneja/cryptid-catalog pull request #13
Opened 2022-11-11 00:36 UTC by agugneja

Created but isn't working. My VSCode is insisting some modules aren't downloaded, wanted to see if it's that or a mistake in my coding. Anyone see an error?

2022-11-11 20:05 UTC, GingerWookiee requested changes

2022-11-11 20:05 UTC, GingerWookiee commented on app.py
> +def create_post():
Shouldn't the CRUD functions be in a repositories folder, not in app.py?

2022-11-11 20:05 UTC, GingerWookiee commented on templates/sightings.html
> +<form>
for your form to work, you need an action="" with a /something that links to a @app.get("/something") or @app.post("/something")

2022-11-15 21:53 UTC, awramos approved these changes
lgtm

2022-11-15 22:06 UTC, awramos approved these changes
lgtm! just need to look at whats conflicting in app.py

2022-11-15 22:13 UTC, merged